### ISSUE TITLE
Error Launching New MLGA Update

### ISSUE THREAD

**Issue by incognitogamer23** [PsiLupan/MakeLobbiesGreatAgain#21]
"No preferences were able to be loaded in or the existing preference file was corrupted.  The existing file has been deleted.  Please restart the application." 

Only happened when the newest update was downloaded.

**Comment by PsiLupan** [comment]
Is it happening anytime after?

I intentionally made a breaking change and said it would delete the file for 1.24.

**Comment by incognitogamer23** [comment]
Any time I try to launch the new update since this morning, I am unable to
get past this error.  Only occurred after updating today.

**Comment by PsiLupan** [comment]
I'll look into it once I'm off work.

I intentionally made a breaking change that would have deleted the file
once. If it's continuing, something else is happening that I need to fix.

**Comment by incognitogamer23** [comment]
Thank you.  For being so prompt, and creating this tool.

It is the one thing allowing this game to be somewhat playable.

Have a nice day,

Andrew aka Altruistic

**Comment by Bollex42** [comment]
I have the same behaviour. This is the output:
C:\Program Files\MLGA>java -jar MLGA.jar
Version 1.24 :: Up to date!
Java Version: 1.8.0_131
Pcap Info: WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
17:41:51.149 [main] WARN org.pcap4j.core.Pcaps - failed to set hardware filter to non-promiscuous mode
17:41:51.159 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet, use default value: null
17:41:51.160 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.inet6, use default value: null
17:41:51.160 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.packet, use default value: null
17:41:51.160 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.af.link, use default value: null
17:41:51.171 [main] INFO org.pcap4j.core.Pcaps - 3 NIF(s) found.
Found: 10.1.1.102
Found: 10.0.0.188
Using IP from textfield: 10.1.1.102
17:41:52.762 [main] WARN org.pcap4j.core.Pcaps - failed to set hardware filter to non-promiscuous mode
17:41:52.769 [main] INFO org.pcap4j.core.Pcaps - 3 NIF(s) found.
17:41:52.774 [main] WARN org.pcap4j.util.PropertiesLoader - [org/pcap4j/pcap4j.properties] Could not get value by org.pcap4j.dlt.raw, use default value: null
Blocks file does not exist. Creating file.
java.security.InvalidKeyException: Wrong key size
        at javax.crypto.spec.DESKeySpec.<init>(DESKeySpec.java:155)
        at javax.crypto.spec.DESKeySpec.<init>(DESKeySpec.java:131)
        at mlga.io.Preferences.init(Preferences.java:44)
        at mlga.ui.Overlay.<init>(Overlay.java:35)
        at mlga.Boot.main(Boot.java:70)

**Comment by PsiLupan** [comment]
Just submitted a new release that should fix the issue.

I made a really, really dumb assumption before.

**Comment by incognitogamer23** [comment]
Downloaded the latest update, and getting this response now : 

http://imgur.com/a/cxzVI

**Comment by PsiLupan** [comment]
Is that happening every time, or just the first time? It will happen the first time.

**Comment by incognitogamer23** [comment]
Every time I try to open it.  I restarted the application as well as my
computer, and still encounter the same error.  Could be a user error on
myself, but I didn't think I launched it incorrectly.

**Comment by PsiLupan** [comment]
Can you run a .bat file as Administrator for it? The original log looked like permission issues for it trying to access your network card.

**Comment by PsiLupan** [comment]
Oh wait, not the same person. Yeah, I'd still say try as Administrator, as I've seen multiple people with this "17:41:52.762 [main] WARN org.pcap4j.core.Pcaps - failed to set hardware filter to non-promiscuous mode"
warning

**Comment by Bollex42** [comment]
The second person with the log is back: 1.25 works for me!

**Comment by PsiLupan** [comment]
Yeah, it's caused by your WiFi card not supporting Promiscuous mode. I've completely removed Promiscuous mode in the newest version, 1.26, as it's an unnecessary CPU load for folks that do support it.

**Comment by darkgusgus** [comment]
I'm also getting the mentioned error from first post on 1.26.

**Comment by Bollex42** [comment]
Everybody is supposed to get the error ONCE as far as I understood. If it persists, please follow the instructions on "How to submit a debug log" from here: https://github.com/PsiLupan/MakeLobbiesGreatAgain

Have you switched from WinPCAP to NPCAP when updating to 1.26? See description here: https://github.com/PsiLupan/MakeLobbiesGreatAgain/releases/tag/1.26

@PsiLupan: 1.26 runs good for me, no errors, no non-promisciuous warnings anymore.

**Comment by darkgusgus** [comment]
Yes error was my bad. Except that it doesn't detect my device anymore. I'm guessing that it's a problem with a LAN card compability.

**Comment by PsiLupan** [comment]
Dark, trying uninstalling NPCap, then rebooting and reinstalling.

I had a similar bug after doing multiple test installs, and that was my fix.

**Comment by incognitogamer23** [comment]
Still getting the same error I originally posted. What am I missing?

**Comment by PsiLupan** [comment]
I'm going to release a new version of MLGA some point soon, which should
narrow it down.

I think it can't get the MAC address from your network card for some reason.

On May 1, 2017 2:01 PM, "incognitogamer23" <notifications@github.com> wrote:

Still getting the same error I originally posted. What am I missing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PsiLupan/MakeLobbiesGreatAgain/issues/21#issuecomment-298403531>,
or mute the thread

**Comment by PsiLupan** [comment]
incognito, can you follow the debugging instructions in the README and get a log? Someone else is reporting one to me as well, but just trying to see if it's the same issue.

**Comment by incognitogamer23** [comment]
Will not allow me to run the debugging.  Tried all troubleshooting tips suggested.  This is what I am now seeing when launching MLGA http://imgur.com/a/xBYno  Gives me the same message as stated above.

**Comment by PsiLupan** [comment]
If you need to, try again with WinPCap. I'm just recommending the move to
NPCap because it gets updated and does have a chance of being deprecated by
Windows.

**Comment by PsiLupan** [comment]
Just wanted to check in if you've had any luck.

I've made a few changes with the recent update to try to address some issues and make the error log a bit more verbose, so that may be able to supply me with any info I need.

**Comment by incognitogamer23** [comment]
http://imgur.com/a/PGcC3

Debug report finally would work.  I have not tested it in game yet, but it appears that the program launched successfully following running the .bat file as an Administrator.

**Comment by PsiLupan** [comment]
Had any luck with it in-game?

Also if you run with javaw instead of java for actual use, you can close the CMD window without killing the program.
